### ISSUE TITLE
Layout issues with SceneCard

### ISSUE THREAD

**Issue by greghesp** [william57m/homekit-react-components#10]
Haven't had time to look at these myself, but there seems to be a couple of issues with the scene cards

There aren't any props to add margins or custom classes to these, however the `homeassistant-dashboard` tries to use them. Also seems there is a vertical alignment issue with the icons

![image](https://user-images.githubusercontent.com/768908/124516550-d704f480-ddd9-11eb-9c61-2a767ae3a9a4.png)

This one looks to be line height for if the scene name is too long.  I believe the line height is whats causing issues with the vertical alignment too

![image](https://user-images.githubusercontent.com/768908/124516555-d9674e80-ddd9-11eb-8ec0-fc947065011a.png)

**Comment by william57m** [comment]
I made a lot of changes + just fixed the text overflow here https://github.com/william57m/homekit-react-components/commit/3b1b52c0dc22f1cb91125978366fb09a99d772b3. It will be released in the next version (1.0.1).
